[workspace]

members = [
    "cli_server",
    "cli_client",
    "accel/xtask",
    "accel/accel",
    "accel/udp-server",
    "common",
    "udp_client",
    "udp_server",
    "socket",
]
resolver = "2"
