programs:
- Router:
    endpoints:
    - "17.0.0.2"
    interfaces:
    - name: router2.1
      role: Fabric
      queues: 1
    - name: router2.2
      role: Fabric
      queues: 1
    - name: router2
      role: Access
      queues: 1
    loadBalancer:
      flowletSize: 4
    inOrder: true

#router2,router2.1,router2.2
